import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/Helixify/HelixCSS@latest/dist/compressed/main.css"
        />
      </head>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
